backend:
  rps:
    host: localhost
    port: 6969
  jwt:
    secretKey: "MySuperSecretKeyForJWTWhichShouldBeLongEnough"
    cookie:
      name: "JWT"
      path: "/"
      is-http-only: true
      secure: true
      max-age: 3600000